### ISSUE TITLE
Problem with the Plugin

### ISSUE THREAD

**Issue by Quix1** [Code12x/WorldTP-For-Multiverse#17]
Hello I have a problem with the plugin, when I add a world and then enter /reloadworlds then it does not work and a red error message comes. History I have created a world /mv create test normal. Then I entered /editworld test test tnt false. Then /worldtp and it said I should enter /reloadworlds which I did but it didn't work (red error).

**Comment by Quix1** [comment]
Please

**Comment by Quix1** [comment]
The command /reloadworlds not work

**Comment by Code12x** [comment]
Hello, thanks for reporting this. I'm going to try to replicate this tonight and see what is going on. Also, make sure your using the latest version of the plugin.

**Comment by Quix1** [comment]
Yes, and this is my server error log(
[latest.log](https://github.com/Code12x/WorldTP-For-Multiverse/files/8307669/latest.log)

**Comment by Quix1** [comment]
at the bottom

**Comment by Quix1** [comment]
If you want please could you add this function it would mean a lot to me I have a cool project. That you can set that if you want to join a world that is password protected (that you can only join with the password that you can then fix.

**Comment by Code12x** [comment]
Ok, I've tested it, and it is indeed a bug. I don't know how I didn't noticed it. I'll be working on fixing it as soon as possible. Again, thank you for reporting it!

**Comment by Quix1** [comment]
Again and again with pleasure, and can you do that with the password vlt that would be so cool

**Comment by Code12x** [comment]
While I do think that would be cool, I don't think I'm going to do that. I want to keep the plugin as simple as possible, and that would add an extra level of complexity that I don't want.

**Comment by Quix1** [comment]
Yes, because I have a project that you can have multiple worlds and the last thing that would be missing would be the GUI with password. Because if someone wants to rent a world with someone else then they don't want everyone to have access to it so with password.

**Comment by Code12x** [comment]
I'll think about it

**Comment by Quix1** [comment]
Thanks because then I have to program this and if you can do that then I would be very pleased

**Comment by Code12x** [comment]
Alright, the bug is fixed now with version 1.3.1
