### ISSUE TITLE
/reloadworlds not working

### ISSUE THREAD

**Issue by R3DM15T** [Code12x/WorldTP-For-Multiverse#21]
Hi, I'm using the latest version of this plugin 1.3.1-resource-update and everytime I do /reloadworlds it comes up with a red error message

**Comment by Code12x** [comment]
Hey, thank you so much for reporting this. I'll check it out as soon as possible tomorrow.

**Comment by R3DM15T** [comment]
Hi, I did some testing around, I changed the plugin Multiverse to Multiverse-Core and the commands now work. Im really sorry for wasting your time.
