### ISSUE TITLE
/wtp as Item

### ISSUE THREAD

**Issue by femabeh** [Code12x/WorldTP-For-Multiverse#33]
How about an item that opens the /wtp menu? One that you get in the set worlds.

**Comment by Code12x** [comment]
Hello femabeh,

I don't think this is something that would be handled by WorldTP. I'm sure there are other plugins that would provide this functionality. I did a quick search and found this plugin [https://www.spigotmc.org/resources/command-items.42556/](https://www.spigotmc.org/resources/command-items.42556/) I don't know if this plugin works in the latest version, but its worth giving a try (it probably does work).

Let me know if you have any thoughts about this.

**Comment by femabeh** [comment]
Hey,
I can understand that it should rather be controlled by another plugin. I've searched a lot but haven't quite found what I'm looking for. I'll probably have to write something myself.
Thanks for the help.

**Comment by Code12x** [comment]
Yeah, that's probably your best bet. Sorry I can't be too much help. It sounds like there is a good opportunity to make a needed plugin. I would do it, but I don't really have the time for it at the moment.

**Comment by femabeh** [comment]
I'll try to write one myself, maybe I'll upload it to my github.
Thanks for the help.
