### ISSUE TITLE
1.20 invframework out.

### ISSUE THREAD

**Issue by FlorisTH** [Code12x/WorldTP-For-Multiverse#34]
![image](https://github.com/Code12x/WorldTP-For-Multiverse/assets/121720811/eed57633-3f9a-416f-9807-d6129214c4c7)

in my earlier review you said you rely on a different plugin (https://www.spigotmc.org/resources/if-inventory-framework.57216/)
that version is out now so when will there be a new version for 1.20?

**Comment by Code12x** [comment]
I see that IF has updated to 1.20.1. I started working on it last night, I will hopefully have it updated tonight.

**Comment by Code12x** [comment]
This should be all good now, https://github.com/Code12x/WorldTP-For-Multiverse/releases/tag/v1.4.3 .

Thanks for letting me know it came out!

**Comment by FlorisTH** [comment]
Its 1.20.1, that also supports 1.20 right?

**Comment by Code12x** [comment]
It should, but I wasn't able to test 1.20 because when I tried to run `java -jar BuildTools.jar --rev 1.20` it builds 1.20.1
